### ISSUE TITLE
Solution not working with raspberry pi 

### ISSUE THREAD

**Issue by alexstyle89** [camilstaps/AN1388-linux#5]
Hello, i have tryed this code to make OTG firmware upload from raspberry pi by serial. Uart is ok and configured, but when code runs, i get no response from device. It stops at line 134, so the data length is 0 . Do you have possible tips for this problem?
Thank you

**Comment by camilstaps** [comment]
Sorry, this is not enough information for me to be of any help. There may be an issue with this code if you are using it in a setup that was not tested, it may not work with newer versions of the firmware since it is no longer maintained, or there may be an issue with your setup. You'd probably get better help in an online community where you can give more details about the situation. Good luck!
